development:
  adapter: postgresql
  encoding: unicode
  database: wimby2_dev
  pool: 15
  username: wimby2
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: wimby2_dev
  pool: 15
  username: wimby2
  password:
