development:
  adapter: postgresql
  encoding: unicode
  database: wimby2_dev
  pool: 5
  username: wimby2
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: wimby2_test
  pool: 5
  username: wimby2
  password: